//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINDERGARDENIS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int ChildrenID { get; set; }
        public string ChildrenName { get; set; }
        public string ChildrenSurname { get; set; }
        public string ChildrenPatronymic { get; set; }
        public string ChildrenGender { get; set; }
        public Nullable<System.DateTime> ChildrenDateofBirth { get; set; }
        public string ChildrenSNILS { get; set; }
        public string ChildrenCHNDOC { get; set; }
        public string ChildrenCHSDOC { get; set; }
        public string ChildrenPolisOMS { get; set; }
        public string ChildrenAddressinSaintPetersburg { get; set; }
        public Nullable<decimal> ChildrenTuitionFee { get; set; }
        public int ChildrenParentsID { get; set; }
        public int ChildrenGroupsID { get; set; }
    
        public virtual Parents Parents { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
