//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINDERGARDENIS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educators
    {
        public int EducatorsID { get; set; }
        public int EducatorsEmployeesID { get; set; }
        public int EducatorsGroupsID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
