//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINDERGARDENIS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Educators = new HashSet<Educators>();
        }
    
        public int EmployeesID { get; set; }
        public string EmployeesName { get; set; }
        public string EmployeesSurname { get; set; }
        public string EmployeesPatronymic { get; set; }
        public Nullable<System.DateTime> EmployeesDateofBirth { get; set; }
        public int EmployeesUserID { get; set; }
        public string EmployeesSNILS { get; set; }
        public string EmployeesPassportSeries { get; set; }
        public string EmployeesPassportNumber { get; set; }
        public string EmployeesPhoneNumber { get; set; }
        public string EmployeesEmail { get; set; }
        public Nullable<decimal> EmployeesSalary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Educators> Educators { get; set; }
        public virtual User User { get; set; }
    }
}
