//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINDERGARDENIS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parents()
        {
            this.Children = new HashSet<Children>();
        }
    
        public int ParentsID { get; set; }
        public string ParentsName { get; set; }
        public string ParentsSurname { get; set; }
        public string ParentsPatronymic { get; set; }
        public string ParentsPassportSeries { get; set; }
        public string ParentsPassportNumber { get; set; }
        public string ParentsPhoneNumber { get; set; }
        public string ParentsEmail { get; set; }
        public int ParentsUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Children> Children { get; set; }
        public virtual User User { get; set; }
    }
}
