//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINDERGARDENIS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int ScheduleModeTypeID { get; set; }
        public int ScheduleDayOfWeekID { get; set; }
        public int ScheduleActivityID { get; set; }
        public int ScheduleStartTimeID { get; set; }
        public int ScheduleEndTimelD { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual DayOfWeek DayOfWeek { get; set; }
        public virtual ModeType ModeType { get; set; }
        public virtual Time Time { get; set; }
        public virtual Time Time1 { get; set; }
        public object StartTime { get; internal set; }
        public object EndTime { get; internal set; }
    }
}
